# Generated by Django 4.0 on 2021-12-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('conductor', models.CharField(max_length=50)),
                ('artists', models.TextField()),
                ('pieces', models.TextField()),
            ],
        ),
    ]
