# Generated by Django 4.0 on 2021-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='ensemble',
        ),
        migrations.AddField(
            model_name='event',
            name='composers',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='artists',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='pieces',
            field=models.TextField(max_length=100),
        ),
    ]
