# Generated by Django 4.0 on 2021-12-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0002_rename_location_event_ensemble_event_composers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='event',
            name='conductor',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ensemble',
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.TextField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='musicians',
            field=models.TextField(default='default', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='composers',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='pieces',
            field=models.TextField(max_length=300),
        ),
    ]
