# Generated by Django 4.0 on 2021-12-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0003_remove_event_artists_remove_event_conductor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='musicians',
            field=models.JSONField(max_length=300),
        ),
    ]
