# Generated by Django 4.0 on 2021-12-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0004_alter_event_musicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='conductor',
            field=models.TextField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ensemble',
            field=models.TextField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='composers',
            field=models.JSONField(max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='pieces',
            field=models.JSONField(max_length=300),
        ),
    ]
