# Generated by Django 4.0 on 2022-01-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0005_event_conductor_event_ensemble_alter_event_composers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
    ]
