# Generated by Django 4.0 on 2022-02-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0007_alter_event_composers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='composers',
            field=models.JSONField(max_length=200),
        ),
    ]
