# Generated by Django 4.0 on 2022-02-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0008_alter_event_composers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
