# Generated by Django 4.0 on 2022-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchtool', '0009_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.TextField(default='Orchestermusik', max_length=100),
        ),
    ]
